# Generated by Django 4.1.13 on 2024-06-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('TipoTrabajo', models.CharField(max_length=100)),
                ('LugarTrabajo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
