# Generated by Django 4.1.13 on 2024-06-05 04:39

import Bodega.models
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('NombreConsola', models.CharField(max_length=100)),
                ('MarcaConsola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocalidadDistribucion', models.CharField(max_length=100)),
                ('siglaDistribucion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDeBarra', models.IntegerField(unique=True)),
                ('nombreJuego', models.CharField(max_length=250)),
                ('consola', djongo.models.fields.EmbeddedField(model_container=Bodega.models.Consola)),
                ('distribucion', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=100)),
                ('unidades', djongo.models.fields.EmbeddedField(model_container=Bodega.models.Stock)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersonal', models.CharField(max_length=255)),
                ('rolId', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$')])),
                ('usuarios', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ubicacion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUbicacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
