# Generated by Django 4.1.13 on 2024-06-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consola',
            old_name='MarcaConsola',
            new_name='marcaConsola',
        ),
        migrations.RenameField(
            model_name='consola',
            old_name='NombreConsola',
            new_name='nombreConsola',
        ),
    ]
